//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almacen2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_venta
    {
        public int id_detalle { get; set; }
        public int precio_venta { get; set; }
        public string id_producto { get; set; }
        public int id_venta { get; set; }
        public int id_tipo_pago { get; set; }
        public int numero_cliente { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Producto Producto { get; set; }
        public virtual Tipo_pago Tipo_pago { get; set; }
        public virtual Venta Venta { get; set; }
    }
}
