//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almacen2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        public Pago()
        {
            this.Venta = new HashSet<Venta>();
        }
    
        public int id_pago { get; set; }
        public int numero_cliente { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public int id_tipo_pago { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Tipo_pago Tipo_pago { get; set; }
        public virtual ICollection<Venta> Venta { get; set; }
    }
}
