//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almacen2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public Producto()
        {
            this.Detalle_venta = new HashSet<Detalle_venta>();
        }
    
        public int id_producto { get; set; }
        public string nombre { get; set; }
        public int precio { get; set; }
        public int stock { get; set; }
    
        public virtual ICollection<Detalle_venta> Detalle_venta { get; set; }
    }
}
