//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almacen2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rol
    {
        public Rol()
        {
            this.Camaras = new HashSet<Camaras>();
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int id_rol { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<Camaras> Camaras { get; set; }
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
