//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almacen2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public Venta()
        {
            this.Detalle_venta = new HashSet<Detalle_venta>();
            this.Reportes = new HashSet<Reportes>();
        }
    
        public int id_venta { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public int numero_cliente { get; set; }
        public int id_usuario { get; set; }
        public int id_pago { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual ICollection<Detalle_venta> Detalle_venta { get; set; }
        public virtual Pago Pago { get; set; }
        public virtual ICollection<Reportes> Reportes { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
